### ISSUE TITLE
FileWatching does not work on Linux

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/mocha-watch#11]
@papandreou reported on gitter that he tried it out on Ubuntu Linux and that it ran all the tests on the initial pass, but then didn't run anything on subsequent changes.

**Comment by papandreou** [comment]
The tests were actually rerun on the first change, but subsequent changes were ignored.

**Comment by gustavnikolaj** [comment]
I found the problem - you had `mocha-watch` installed, not `@gustavnikolaj/mocha-watch`. We really need a new better name at some point :-)

**Comment by papandreou** [comment]
Hahahaha!
