### ISSUE TITLE
Alternative name - mocha-watch is taken on npm

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/mocha-watch#12]
There's already a package named [mocha-watch](http://npmjs.com/package/mocha-watch) on npm. This package is released as [@gustavnikolaj/mocha-watch](https://www.npmjs.com/package/@gustavnikolaj/mocha-watch) and has already caused some unfortunate confusion (#11).

I'm very much open to suggestions for a new name :-)

**Please make each suggestion in a separate comment so we can use reaction-emojis to vote!**

/cc @alexjeffburke @papandreou

**Comment by alexjeffburke** [comment]
mocha-glare
mocha-watcher
watch-mocha

**Comment by gustavnikolaj** [comment]
I'll leave the boring option here:

**mocha-watch**

Or, in other words: Reach out to the owner of the mocha-watch package and convince him to handover the package name :smile: 

https://github.com/paulpflug/mocha-watch

**Comment by sunesimonsen** [comment]
mocha-big-brother
mocha-nsa 😜
mocha-goggles
mocha-blinded


Sorry I bad at naming 😂

**Comment by alexjeffburke** [comment]
Liking this thread already, it was bound to get interesting :) More thoughts:

mocha-peek
imocha (watching inodes or something?)
mocha-seek (another filesystem pun I guess but it does seek out your tests)

And of course, there is always the boring option. I also like mocha-tower btw, either it's towering over mocha or it's short for watchtower. PS I feel terrible at this too!

**Comment by alexjeffburke** [comment]
mocha-mon

actually this is the fav of mine so far - executing it reads "mocha monitor <files>"

**Comment by gustavnikolaj** [comment]
After intense discussions on the unexpected gitter channel we landed on imocha. The rename has been done and the old package is deprecated. I'll move the repo over shortly.

**Comment by gustavnikolaj** [comment]
Thanks for your help guys! :rocket:
